export type WhitelistSeedItem = {
  word: string;
  category: string;
  subCategory?: string;
  weight: 1 | 2 | 3;
  synonyms?: string[];
};

export const NEWS_STOPWORDS = [
  "的",
  "了",
  "是",
  "在",
  "与",
  "及",
  "也",
  "又",
  "将",
  "等",
  "为",
  "于",
  "之",
  "本次",
  "本届",
  "此次",
  "相关",
  "进行",
  "表示",
  "提到",
  "发布",
  "点击",
  "详情",
  "官网",
];

export const NEWS_PENDING_BRAND_BLACKLIST = [
  "中国",
  "全国",
  "本次",
  "本届",
  "行业",
  "家居行业",
  "定制行业",
  "企业代表",
  "相关负责人",
];

export const NEWS_BRAND_SUFFIXES = ["木", "木业", "木作", "家居", "家私", "整木", "集团", "国际"];

export const NEWS_BRAND_CONTEXT_PATTERNS = [
  /品牌[:：]\s*([A-Za-z0-9\u4e00-\u9fa5]{2,10})/g,
  /参展品牌\s*([A-Za-z0-9\u4e00-\u9fa5]{2,10})/g,
  /由\s*([A-Za-z0-9\u4e00-\u9fa5]{2,10})\s*打造/g,
  /([A-Za-z0-9\u4e00-\u9fa5]{2,10})亮相/g,
  /([A-Za-z0-9\u4e00-\u9fa5]{2,10})发布新品/g,
  /([A-Za-z0-9\u4e00-\u9fa5]{2,10})携新品参展/g,
];

export const INDUSTRY_WHITELIST_SEED: WhitelistSeedItem[] = [
  { word: "图森", category: "品牌", weight: 3 },
  { word: "木里木外", category: "品牌", weight: 3 },
  { word: "华木定制", category: "品牌", weight: 3 },
  { word: "整木定制", category: "品类", weight: 3 },
  { word: "全屋定制", category: "品类", weight: 3, synonyms: ["定制家居", "整家定制"] },
  { word: "高定木作", category: "品类", weight: 3, synonyms: ["高端木作", "高定定制木作"] },
  { word: "木作定制", category: "品类", weight: 3 },
  { word: "高端定制", category: "品类", weight: 3 },
  { word: "实木定制", category: "品类", weight: 3 },
  { word: "别墅整木", category: "品类", weight: 3 },
  { word: "高端整木", category: "品类", weight: 3 },
  { word: "整木家装", category: "品类", weight: 3 },
  { word: "欧派", category: "品牌", weight: 2 },
  { word: "金牌", category: "品牌", weight: 2 },
  { word: "索菲亚", category: "品牌", weight: 2 },
  { word: "志邦", category: "品牌", weight: 2 },
  { word: "尚品宅配", category: "品牌", weight: 2 },
  { word: "顶固", category: "品牌", weight: 2 },
  { word: "好莱客", category: "品牌", weight: 2 },
  { word: "皮阿诺", category: "品牌", weight: 2 },
  { word: "玛格", category: "品牌", weight: 2 },
  { word: "诗尼曼", category: "品牌", weight: 2 },
  { word: "百得胜", category: "品牌", weight: 2 },
  { word: "科凡", category: "品牌", weight: 2 },
  { word: "客来福", category: "品牌", weight: 2 },
  { word: "广州设计周", category: "展会", weight: 2 },
  { word: "中国建博会", category: "展会", weight: 2, synonyms: ["广州建博会", "建博会"] },
  { word: "上海建博会", category: "展会", weight: 2 },
  { word: "乌镇国际设计周", category: "展会", weight: 2, synonyms: ["乌镇设计周"] },
  { word: "全国工商联家具装饰业商会", category: "协会", weight: 2 },
  { word: "中国家博会", category: "展会", weight: 2 },
  { word: "深圳时尚家居设计周", category: "展会", weight: 2 },
  { word: "设计周", category: "展会", weight: 2 },
  { word: "高定展", category: "展会", weight: 2 },
  { word: "家居展", category: "展会", weight: 2 },
  { word: "新中式", category: "风格", weight: 2 },
  { word: "轻奢", category: "风格", weight: 2 },
  { word: "极简", category: "风格", weight: 2 },
  { word: "现代风格", category: "风格", weight: 2 },
  { word: "现代简约", category: "风格", weight: 2 },
  { word: "法式轻奢", category: "风格", weight: 2 },
  { word: "意式极简", category: "风格", weight: 2 },
  { word: "侘寂风", category: "风格", weight: 2 },
  { word: "奶油风", category: "风格", weight: 2 },
  { word: "中古风", category: "风格", weight: 2 },
  { word: "定制家居", category: "品类", weight: 3 },
  { word: "整家定制", category: "品类", weight: 3 },
  { word: "橱柜定制", category: "品类", weight: 3 },
  { word: "衣柜定制", category: "品类", weight: 3 },
  { word: "护墙板", category: "品类", weight: 3 },
  { word: "木门", category: "品类", weight: 3 },
  { word: "酒柜", category: "品类", weight: 3 },
  { word: "书柜", category: "品类", weight: 3 },
  { word: "衣帽间", category: "品类", weight: 3 },
  { word: "楼梯木作", category: "品类", weight: 3 },
  { word: "背景墙", category: "品类", weight: 3 },
  { word: "一体化木作", category: "品类", weight: 3 },
  { word: "万华禾香", category: "材料", weight: 1 },
  { word: "水性漆", category: "工艺", weight: 1 },
  { word: "榫卯结构", category: "工艺", weight: 1 },
  { word: "一门到顶", category: "工艺", weight: 1 },
  { word: "实木复合", category: "材料", weight: 1 },
  { word: "环保板材", category: "材料", weight: 1 },
  { word: "原木", category: "材料", weight: 1 },
  { word: "木皮", category: "材料", weight: 1 },
  { word: "烤漆", category: "工艺", weight: 1 },
  { word: "开放漆", category: "工艺", weight: 1 },
  { word: "封边工艺", category: "工艺", weight: 1 },
  { word: "同色配套", category: "工艺", weight: 1 },
  { word: "无醛添加", category: "材料", weight: 1 },
  { word: "静音五金", category: "材料", weight: 1 },
  { word: "隐形拉手", category: "工艺", weight: 1 },
  { word: "高定工艺", category: "工艺", weight: 1 },
  { word: "别墅", category: "场景", weight: 1 },
  { word: "大宅", category: "场景", weight: 1 },
  { word: "豪宅", category: "场景", weight: 1 },
  { word: "样板间", category: "场景", weight: 1 },
  { word: "会所", category: "场景", weight: 1 },
  { word: "高端住宅", category: "场景", weight: 1 },
  { word: "私宅定制", category: "场景", weight: 1 },
  { word: "全案设计", category: "场景", weight: 1 },
  { word: "整装项目", category: "场景", weight: 1 },
  { word: "上海", category: "地域", weight: 1 },
  { word: "杭州", category: "地域", weight: 1 },
  { word: "广州", category: "地域", weight: 1 },
  { word: "深圳", category: "地域", weight: 1 },
  { word: "北京", category: "地域", weight: 1 },
  { word: "苏州", category: "地域", weight: 1 },
  { word: "南京", category: "地域", weight: 1 },
  { word: "成都", category: "地域", weight: 1 },
  { word: "重庆", category: "地域", weight: 1 },
  { word: "宁波", category: "地域", weight: 1 },
  { word: "无锡", category: "地域", weight: 1 },
  { word: "东莞", category: "地域", weight: 1 },
  { word: "佛山", category: "地域", weight: 1 },
];
