server {
    listen 80;
    server_name newm.cnzhengmu.com;

    location ~ ^/(show-[0-9]+-[0-9]+\.html|list-[0-9]+\.html)$ {
        return 301 https://newm.cnzhengmu.com$request_uri;
    }

    location / {
        return 301 https://cnzhengmu.com$request_uri;
    }
}

server {
    charset utf-8;
    client_max_body_size 128M;
    sendfile off;
    listen 443 ssl;
    server_name newm.cnzhengmu.com;
    root /data/web/zhengmu/web;
    index index.php;

    access_log logs/newm.cnzhengmu.com.access.log;
    error_log logs/newm.cnzhengmu.com.error.log;

    ssl_certificate /usr/local/nginx/conf/cert/newm.cnzhengmu.com.pem;
    ssl_certificate_key /usr/local/nginx/conf/cert/newm.cnzhengmu.com.key;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location ~ ^/(show-[0-9]+-[0-9]+\.html|list-[0-9]+\.html)$ {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location / {
        return 301 https://cnzhengmu.com$request_uri;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        try_files $uri =404;
    }

    location ~ /\.(ht|svn|git) {
        deny all;
    }
}
